{{- range $name, $c := .Values.controllers }}
{{- $cls := index $.Values.global.ingress $name }}
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: {{ $cls.className }}
  namespace: {{ $.Values.namespace }}
spec:
  chart: {{ $.Values.chart.name }}
  repo: {{ $.Values.chart.repo }}
  targetNamespace: {{ $.Values.namespace }}
  version: {{ $.Values.chart.version | quote }}
  valuesContent: |-
    controller:
      ingressClassResource:
        name: {{ $cls.className }}
        default: false
      ingressClass: {{ $cls.className }}
      replicaCount: {{ $.Values.replicaCount }}
      minAvailable: 1
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 0
          maxUnavailable: 1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: {{ $cls.className }}
                  app.kubernetes.io/component: controller
{{- if $.Values.metrics.enabled }}
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
{{- end }}
{{- if $.Values.resources }}
      resources:
{{ toYaml $.Values.resources | indent 8 }}
{{- end }}
      service:
{{- if $cls.loadBalancerIP }}
        annotations:
          metallb.universe.tf/loadBalancerIPs: {{ $cls.loadBalancerIP | quote }}
{{- else }}
        type: ClusterIP
{{- end }}
{{- if $c.externalTrafficPolicy }}
        externalTrafficPolicy: {{ $c.externalTrafficPolicy }}
{{- end }}
{{- if $c.configTemplate }}
      config:
{{ include $c.configTemplate $ | indent 8 }}
{{- end }}
{{- if $c.proxySetHeaders }}
      proxySetHeaders:
{{ toYaml $c.proxySetHeaders | indent 8 }}
{{- end }}
---
{{- end }}
