---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin-exporter
  namespace: jellyfin
spec:
  encryptedData:
    JELLYFIN_TOKEN: AgA/v6i5rFhiCrge2BNXVgk3ONlUODS9QaYdtdY5CfBcRM2HZHy10anflt+oAl1RV9GYPCo/GTzIRBn0B85hvnh7Drj9SEJZW1I/zYIrbDMi7IXFP1YkDHTpfzrP5qCd8k9sz6J2Zo3NT0Kw+kpYjy6jc31nb22qdIEamuLERsh6TV/3+GLhq5maNTYAsTZc29zrsAei8DNOEtdi6VSeAEcuAGf0MAp964VyGOGyINFFF0yB/9sa1xpti7F3jVOId3DZhwEMXDlLnTopwlbmGeh098keqFceJYzQvSUQJ3SqNV7Y3YUI112FQrlxLjzumuN8bHUPIXHreMlju6f46rojAk8ZHtnywdK5RH0oXSHYa+2og3I6ecoWkotO9+WwNfa2v5Wy8qdrUX1nunhb8+CCb9Pj28GbIa0xWRfHrQPD4Y68QR0BGU7VNidfZ++K6Wy5SnKrPCFSa3avjMA08+fsWJ1CISPDbwBrfuI1alIxxFSIjo8GHCTgMVe4kYM0R9F5G1PWF9WAI9htuVD2Mwd7rQd0g1vdzX65YaDK6zgzntPL+lBhHE/vJla8Rgj7hoSvqlay+SVDePU7MIbxPk7heR3ZV5UAEfHA++1zuzVmf5IVnXzMgIAT0qYqjnFimaDgME7NEXnLmVEGp0iMqebXwtNoHux22wXQe6btspqpjJRTnENkRQxrDH7IEMXWna43uY07xZGqOr4/B6LJXsrssuPMUJ+XxozbdEhLmhmFtw==
  template:
    metadata:
      name: jellyfin-exporter
      namespace: jellyfin
