---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_POSTGRESQL__PASSWORD: AgCN+4jG/ylPfMIj67DhKvTEdmxxgtYZbAimOhUnljf+oB3yljda1WfPIsu4WK7IN7FgJyq5Ni3jsTPKkDXN49bW6pmzV0ji3oXwH4az3xANDu/GkfMRE2DOTovOfh0uny8XqbIcibD0muSlLR9SBlYUbh4UaHb+kjFTraxjsv52xCDV78KWpnEPBGyyxi7NiuFRCcbBT/Qj7nsNGImiBliN76WMSig8mc0D6WctOzRQbQ4ouAhV3NzeTkfY0Z7qo0qyzJU6nGJmqEqqoEzJCWm/ov6HTdoCE/CySvBquzQavvOB3DWRz6vhM+7hXQrV+Dx7Fkse7RJUr+CyQbi7uTwvd/i8+o98Zq7N/yt+8UQ0aqQK9TrTYUDUIfbvBWqXH2VH6w0bU9qU2/nCUZ5t2BJhA5IoWwAmGu4Vb83fMBtoXn3AW1o8TxQRJbGXddsxSC243xkPAbOa1UNA3sUGecyk1mJiUjNXjLLuyC6GGkaStPd7DdmG+jeV8gR22owbkiXl2XThNE1WUu958bma8e42uZYrXJo8VLIGauNJmFXszyT06r2fvXCrv/ow0aSLIjqhavEnel+Dnx2eq88dtVRqAJzKuJHax9CS2cSxlJcE7svrdXYYqIpQAJT4xrn2ohwp5lL3Av/BkKR0khvdT31YhwqFGZ2M4g9DsEcTpYp1A6fQDfjnf+s/7aFZ2CK+2PiRsvpVVmUT8hI=
    AUTHENTIK_SECRET_KEY: AgBMrUd5mGanvyziDDbDfEeQybqm80Rfg/BhsIXtO66YzH1UEeiIN6XR2jLZw1fR9OkZtSIyMOlosy/dduesKsmImUVTk7eCOoa/DNvtjUxPG8bXfB6aclltmgW1UzHfi1hIvvCvw+lyxfIh748Yu6g+f/XDtOAndox9ypzFFAm6UhilgY4j08DslRU/7EVsUCc1VhKJ+KCTU09p5vu/2GTWCni1FT6908ZnFm6LUHamhdJr19jDXX803mm/4oO++lCyjvbJMdSLnm05T845vobS/2mr1sKobRENAxXPeq4tt6YCDPA0cw5A1qmZvah3rSUn0BHIJ0qaEzXBhk2l1QnI6gfltVCOI0w5nkWAgHF+Z665SVu6MvImx76SPBlJfv/LwXKaFiK9hvzdXfU1gaBiDloUCluJGHZREHxbeCaHptpePD7Jua/tyR+TCYLD/yZ47RiCWd+vT/xISpiDdkG9WSj4W8O1OPH9JOVtduhW0NaZUbk1Ry65Nk/09FndKBzpb35FjkesFwXo98SCduUdp3tlr3XyMihggqAMxKXe8HP7R5sMfYj70e+39wfYBz4R51qNDExK3c8v5fgkOga5PgYQNW+ydjOYd277AW9NKIi8o71dNGVavBRGRdEsXZnj3XC4uHitP/o8K+5jU9C1Xc3JIv4cw9d/eSRHPHQTgJbp1gDUzegmjxlFbrwsrNNL+fVX4aqYKxcBoo+s10yCob65jOMyItrpAs27o+vcP+6p5SnMXoIgGIknAg==
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
