---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_POSTGRESQL__PASSWORD: AgCiBay04f15Rs/PWRnNHADVfB01QVRpdw7dXJcq/NPVxyX5hOTiXlVgyDJSQmLToLN0PgeXAmuhnEbm6vH37A2JOjhgFmxSrgCrrN/5JnOajsFPdXxCRkSvTUpDYxJaIUdgd6EcZ16wLUBDShmmydQYh+B7y9K8+EMXl6DZxkrS+QExnyCQ+t++OmMJSM9tanQSIUc/GK96OeIu4Kc1u5ZfthydkCPxRGH/lMURPK7WleRPARlFqzl/J126Y2WIRGpCEMGPJxEz28PzKwaxHCeIMyU+Krsvg3GIWB55LfUbNW3KfgUo+8L2nrxq5oj/P6i//TjR8y8l9QQv0+auP1hWJkw0wjOcc+7UgeyjrrK8eeGS9jL9b2/nRsX4F2QJbf7ps8pxw1bTMFG6uqlHG6SipXf22GcsRp6/iXJOso7u9v5/cMoB3f0GJtTC5i8sQR0swpXT0Si826eKs47gqOReWD109BEugmSIiFB+RbxMmxCZLepgMZZTr6VdptZSK4w5M2Upjc+j7NzNPl2tbWuJjaxYQf5vuoKis2LSEND54H5Fes7DrgfDPEDR4Hhu1bmVZU2J0Ll0G2NajdzcpxBTf7XtYQNuoT7/om84trxnTFD1HDC7CMu+mwclEeXIiRX7C2NAKFJhA4DORAMlWJRb/Brx/sw+SYieDN4oyYOMvCTS3UJ200knWIRUUP/m99a3DTQFVUVa9pI=
    AUTHENTIK_SECRET_KEY: AgArlWEr0T6VT7lRvx1B8Vt866z5Oapt7xScmZHSS2M61JXlPAWwQEqLV3Q7OAEYZ97gqcFnMUj7tnTzCWmkkNQq1kz89UvQ8K0tgYUktLBQmpiU2Tr9PFKf1Thn9hJkmQaqGEMIXb0Pe/yP2MQI9z0cIpMj+xCJgljEaCc6TTz3SVfOWFHtZMiExS2jR3zgPV4Qrv6OpNjdrXuL1u34qT0gI7LdaDHA+nr+cOR9BEP6Hp8Ek9gxYEn1Cw0sKFsFAxoFTY1DNmQ368W8Ygvc+thbuLWXc08wMzOx+Gv3tqufAdx603H1NEIEhNB8PF5RTk7OuQIxnndRxlh5USY6c5S6pPikgzPkmBBGM3XSSu+1z5Ve8Tpu3r8OGxBrGJ32Dd0tojR34sVPGW495kDPmz4GamSGCLAxOLEgFhA7dK/GBAgm4FdiG9ZRaZxLDHcbC9gN0zB47eYpEuoBQ3Jd21wLqKrNyBik3e6+up4hzpv4+beAjljbRqz1xCWF++xD7fha3BxnxfDAxbEnrXzeNP14StgXNK7mbWr7wtdUtl24tHVoP/qy06PXoVqVXy3KCqgsYnhGX/yQpeBpBcAMU99yw7dZtPWuXRQfe2WOIBmnjKrZMjZuTGs1JuWpKZ/ianan2Sgwy/35IfSrq8I1XCYJwSRKcQNU5Mq7I4GtzLqM4kB5OdWSmjdNkZKsCdHgKYFiN8Y2ZqXn9v0loGWUUkZ14L2I5/dP2tjlCWMvIIW08796y6rTHKKKZO798Q==
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
