apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipAddressPool.name }}
  namespace: metallb-system
spec:
  addresses:
    {{- range .Values.ipAddressPool.addresses }}
    - {{ . | quote }}
    {{- end }}
