apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  labels:
    homelab/tier: apps
spec:
  project: default
  source:
    repoURL: https://github.com/glazrtom/homelab.git
    targetRevision: HEAD
    path: authentik
    helm:
      valueFiles:
        - ../global/values.yaml
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
