apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: argocd
  labels:
    homelab/tier: apps
spec:
  project: default
  source:
    repoURL: https://github.com/glazrtom/homelab.git
    targetRevision: HEAD
    path: media/application
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
