- name: Install Helm
  become: true
  ansible.builtin.shell: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: List installed helm plugins
  become: false
  ansible.builtin.command: helm plugin list
  changed_when: false
  register: helm_plugins

#- name: Install helm-diff plugin
#  become: false
#  ansible.builtin.command: helm plugin install https://github.com/databus23/helm-diff --verify=false
#  when: "'diff' not in helm_plugins.stdout"
