apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core
  namespace: argocd
  labels:
    homelab/tier: core
spec:
  project: default
  source:
    repoURL: https://github.com/glazrtom/homelab.git
    targetRevision: HEAD
    path: applications/core
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
