apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://emberstack.github.io/helm-charts
    chart: reflector
    targetRevision: 7.1.262
    helm:
      releaseName: reflector
      values: |
        replicaCount: 1

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

