{{- if .Values.global.monitoring.serviceMonitors }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - argocd-metrics
          - argocd-server-metrics
          - argocd-repo-server
  endpoints:
    - port: metrics
      interval: {{ .Values.global.monitoring.interval.slow }}
{{- end }}
