namespace: authentik

app:
  name: authentik
  domainPrefix: authentik

service:
  name: authentik
  port: 80

authentik:
  global:
    envFrom:
      - secretRef:
          name: authentik-secrets

  redis:
    enabled: true

  postgresql:
    enabled: true
