namespace: pihole
replicaCount: 1

image:
  repository: pihole/pihole
  tag: "2026.07.2"
  pullPolicy: IfNotPresent

volume:
  config:
    size: 2Gi
    storageClassName: longhorn

dns:
  loadBalancerIP: 10.0.0.200
  internalIP: 10.0.0.150
  upstreams: "1.1.1.1;1.0.0.1"

domainPrefix: pihole
