global:
  imagePullPolicy: IfNotPresent
  namespace: media

defineGlobalPvc:
  enabled: false

prowlarr:
  enabled: false
  image: linuxserver/prowlarr
  tag: latest
  volume:
    config:
      size: 1Gi
      storageClassName: longhorn
  vpn:
    image: qmcgaw/gluetun
    env:
      VPN_SERVICE_PROVIDER: windscribe
      VPN_TYPE: openvpn
      OPENVPN_SECRET_NAME: windscribe-auth
      OPENVPN_SECRET_USER_KEY: username
      OPENVPN_SECRET_PASSWORD_KEY: password
      SERVER_REGIONS: Czech Republic
      DNS_KEEP_NAMESERVER: "on"
      FIREWALL_OUTBOUND_SUBNETS: 10.42.0.0/15

radarr:
  enabled: false
  image: linuxserver/radarr
  tag: latest
  volume:
    config:
      size: 1Gi
      storageClassName: longhorn

sonarr:
  enabled: false
  hostname: sonarr.internal
  image: linuxserver/sonarr
  tag: latest
  port: 8989
  volume:
    config:
      size: 1Gi
      storageClassName: longhorn

readarr:
  enabled: false
  name: readarr-books
  hostname: readarr.internal
  image: lscr.io/linuxserver/readarr
  tag: develop
  port: 8787
  volume:
    config:
      size: 1Gi
      storageClassName: longhorn
