global:
  imagePullPolicy: IfNotPresent
  namespace: media

defineGlobalPvc:
  enabled: false

prowlarr:
  enabled: false
  app:
    name: prowlarr
    port: 9696
  image:
    repository: linuxserver/prowlarr
    tag: "2.6.1-nightly"
  ingress:
    enabled: true
    external: false
  volumes:
    config:
      create: true
      size: 1Gi
      storageClassName: longhorn
      mountPath: /config
  sidecarsTemplate: prowlarr.vpnContainer
  vpn:
    image: qmcgaw/gluetun
    env:
      VPN_SERVICE_PROVIDER: windscribe
      VPN_TYPE: openvpn
      SERVER_REGIONS: Czech Republic
      DNS_KEEP_NAMESERVER: "on"
      FIREWALL: "on"
      FIREWALL_OUTBOUND_SUBNETS: 10.42.0.0/15
    secretEnv:
      OPENVPN_USER:
        name: windscribe-auth
        key: username
      OPENVPN_PASSWORD:
        name: windscribe-auth
        key: password

radarr:
  enabled: false
  app:
    name: radarr
    port: 7878
  image:
    repository: linuxserver/radarr
    tag: "6.3.0"
  ingress:
    enabled: true
    external: false
  volumes:
    config:
      create: true
      size: 1Gi
      storageClassName: longhorn
      mountPath: /config
    media:
      claimName: media-pvc
      mountPath: /media

sonarr:
  enabled: false
  app:
    name: sonarr
    port: 8989
  image:
    repository: linuxserver/sonarr
    tag: "4.0.19"
  ingress:
    enabled: true
    external: false
  volumes:
    config:
      create: true
      size: 1Gi
      storageClassName: longhorn
      mountPath: /config
    media:
      claimName: media-pvc
      mountPath: /media
