{{- if .Values.defineGlobalPvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-readarr-books-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.readarr.volume.config.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.readarr.volume.config.size }}
{{- end }}
