{{- if .Values.defineGlobalPvc.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-media-media-pv
spec:
  capacity:
    storage: {{ .Values.global.sharedMedia.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-bulk
  volumeMode: Filesystem
  claimRef:
    namespace: {{ .Values.global.namespace }}
    name: media-pvc
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: {{ .Values.global.sharedMedia.name }}
    volumeAttributes:
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      share: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.sharedMedia.size }}
  volumeName: shared-media-media-pv
  storageClassName: longhorn-bulk
{{- end }}
