apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: {{ .Values.namespace }}
  {{- with (.Values.ingress | default dict).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.internal.className }}
  rules:
    - host: {{ .Values.domainPrefix }}.{{ .Values.global.domain.internal.suffix }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 32400
