apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-plex-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.volumes.config.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.config.size }}
