apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    loglevel: debug
    transport-loglevel: debug
    ingress:
      - hostname: '*.{{ .Values.global.domain.public.suffix }}'
        service: http://nginx-external-ingress-nginx-controller.ingress.svc.cluster.local:80
        originRequest:
          noTLSVerify: true
          originServerName: "*.{{ .Values.global.domain.public.suffix }}"
          logHeaders: true
      - service: http_status:404