---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBzu1CnyYDohJh603rPKL2iCwif7JCPNY7P/1oAXtEumK+iYX3QklEEWdxnMEXuua0ZET/VcAm2ssKPssmU76sE37kc/KX4z+JjTkw4TOa3XrwBWhFVXt1UjTmcWVReXbwHwigorA4W5gn8qFpFk+UBiH59DtgbF77NlTPEUXdbkzgd/jm5E6vTNepiBw58tM0tNYIMovLuapKyXYOtIEA/lEPBGejCT2RFsIVz1R5m7iY60GhonIUSfWIh0y/QjFUcpMg5nvNFXqg/RqYBbLum/cS1xILihb0opADqKI2cnWDflVadcXlQghtNORryg+7wsGOF8LEl2Ae6FJdwL7e+YoTt1j9Cugf3/N4Wmd9Y3JtoWavDHWh92Ey5qhuDAFvjp1xvmlweU4KITaSD/590ehkCIC3/jy0iCCadgUCXbT2VAAG2bSeFM6M2ommzAn634LLrIm3pIFLj0QUIYyZuP7rF2qBKBPu7eKi9/Ei3TJDx8AsD+uw26xIqmphUsn4DFXX5kAJcBZ4Ht5N+t9mZsL7jQO2goYadRR625GZRi5GY1/zfr+PsTOwD+1C926JZS96fN1gKRSdQIO1DNPL9z0dYnIHn9Y4kXjXuzdJantoaXWrkiRROm3TjC1eTa8OQu0VuLWTm3tM2GY2j5cJ1TyychQqRi8WnvDwuhRXRUVIGnd9M6ghh5L8SLHFLEagG8gBASNo2Zc8cPtN0Q2aLyec0eQLJVeUqN8XFmrejkKnSjjfzjQQisAEAGjazuyR3kuT7kfT3WG2i/HlLfSEw8qcbfO6SQCbhIGreqffoX64F8Suf0fXN0EP9tYxbJtYqPn6EB1q+S4qjBJVXgHuP721xLa2mRO3Oi5uoV2+iEYv0ZmbvE0H+e3vJoGHpgI81ADIHt3Zs5n9yjb+9wc/v8w4CXBEVT/GW8/TLpgQoXoEXV8w=
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
