{{- if .Values.global.monitoring.serviceMonitors }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pihole-exporter
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selector:
    matchLabels:
      app: pihole
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.global.monitoring.interval.slow }}
{{- end }}
