---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCP1xNwukrITm6PjJ0O/o+OHpSRy+/KPsDWWfL4lLQUeMxTw8mMNRIRNUSL3SREdiCJGHS15SwIOpcm7/q0qehe8sllq68qlzXjMJgoNvvH7IITtO7r1LrfwoBUS1guz1R4Vvf+Hw2OJtL9nseq/X5KGPKuenguRn6L3U7QlXq7MmOpeRqt9cpLxuifmw0ff/LBOsXp1J/lNlAps3E1EO/M7awO+aTup5jSaishi7zIG5LBEpjR8kAYzObukYmD7hbUi0VI7+Pm/zOsPOfRnnOAR/lfuz4Ciq832lg6rqubZmoVyKR2/R+Qk0set9aMmLqtPK8BuF3SMl2YLJroXIp/qYXb0Oy8svKlY16I0Hwso5j7n80AqftolieD4pTHuulepoOfJ/VF9OmhWLe+U+A3JXqKmntFcAduTd+0LA0lHruT9eGeY4LKZMY/ySUA0BQJCTSbE54iR95oFvomqCKuoBnVPCm2kjsbtS5Q5M0iSA/8iGStET8jWjCB43C/jm5QaPxxFq6eKT1skarTXc5g/ECV8wQxM9sYY1IM59wqL0c24vwecDw57qYZuI4x1TDjOVrJYIPfRVAhZAe92KqXmVMyucXkYjbzGf8ofdwhxgWgFb1MpZN3wPzrUDofZGmUC1Y7/gO0ttDQ2e+3a3dhJ3RliVOFHbM0BuSCNvS8GK5ISzdb6LqIyLna3LhjUelLRFeu9Fa2xZlpd8rshi2iGnWuq3zr+nfDpNTd4BRGRQ==
    ADMIN_USER: AgAcxQ6SoVg2FUl5QSoKb88EJi9daFu+xneBWyED2M2/n7EC62lnpQACQSAY/NM6cazjowqygRNK8sAan3fTG5yaTWNQD6pN9DPL3L5pj2P11Vj4VrXIzw6BZxqW2LJakL8JpvAGjnMJ5FdmEuiNsdog8dAjKlAnxsT59kp7ffrWbYhtfIugT2tamGBxJSq3CjUJEhhbVIs4YY889PwII/6jZLCytkg740GUi9XZredLlGak/oA0bCIvA3C7efuhuMVUtZ33gW5JOm5Mv2g/W9coVU4QW7CJz9qRyjp8ieDEt+4EPMHGke98ueYYhEbpAsUNIia8ZROoetpuSGBZVSJFveJYnQNCpfMm2ANKVo0Ioph/OZj8d/4+fCDN2JxxGaD9Nt8jsnyRpS+XoIgS5SRtKWfEAXkx6L1UQr063sU95Zq5lGmH7rWmvPI6UT7KTqiDTjk+7BlZ1Y6+FBzxRM0pTz45gGyBJrkhfRLWhHxGFHpml5X1bmRiB17RKqZN6ei/2kYtSlIUYxcumAw3L+TRRgWEwfpyS8gK9J9Is983sV3n25Vel5J0AmOxvLho0mpxZAMNbQLTRoTD+UTMwdE8Xo4ky+TTbkp7Kj35mP1zfdtZqLiPUGT+bLLkLqXaHb+gfgEM60Nv2zN3JWflknh8IbkqNLaU+XW99SXWu3v/eAGIrChZWnHy+MzM7jcHUUOBN4yM3w==
  template:
    metadata:
      name: monitoring-grafana-admin
      namespace: monitoring
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-healthchecks
  namespace: monitoring
spec:
  encryptedData:
    PING_KEY: AgChylArRULsd6fIpMioqNOCK5/lckWWXiSMhvML9CQBly2Nn1WXHYaJY7tn5WFrdttBA0X4ZB/WuNHiyaqEjGucqsw0QUTRxIgkKblxvp6obGiXQvjoHTXYnpKVNxQ6toRuqSY4EmrmSd1RKJLwYXsX4cW0tcFC6ziF1cp9652ZThKSubl3+j1oJ4irvWTuqubSnsrK8ZiGIaz2CxZkmiYdqc40J00CPiFWXaKLq/5jX/UaMjP/fhB7JqAP1QUkFqvQ3J0taOpEqCQfbfnkCyluUEP8M23qvAeOuLQZeMkzwDnZPO5xi9p0zWRpnQxJ90056OpkPGzSS8WjdBPYsmta0PFSv4cmJDJKXQSvpDSpqqQlxRPs5bbcbUZYPik2kRfKDCkHKp637NZEsZ6QMY0LD21kVLGXRh3YNvAK2LL3JkSNJvBwZ71JyWh8IbWBD5WZ3PH+rfePspPzL3AoG3MUmuZdhTgSqRceSuZusVzEcj1xdvi+Z+yGIxerhpDyhzThgclih7gtEoXWDpB57Bx+WKazb5BXMdMKZ2xZEvY6LUQw2QCus7wxYMQBZRU8jbBS+JfgsYt+MrD2QqEdc7J4aHzV6ERXkGUwYnzwlEsv4nBe4nciTJ7mO9RbAnhvAKzVBeT7R2Db3rQSjQJBVHdYnqBHrPtvBuewbjqcIJH+/U7q98DED4wKgGEDN4XokjgVsHUoPJ0T4XuS9BD/Tv+XMH2NhiKy
  template:
    metadata:
      name: monitoring-healthchecks
      namespace: monitoring
