---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_POSTGRESQL__PASSWORD: AgBv9mDoUkOgBnXKRDG8SDqd6v2iznstv3wAqUeyvc6VjgTVRSPV+6QCui3VDaR1OBdqrXMMet92SW7ZNaeyYB6bF4rQvuMQHhSm8ReWnJBa5u7eGLb+teyc5O9FHIDknlAgjtekfoYB+oI0a9lWMeKS2NxfM/rI7/iJ8KqwIXlMqTjqYfw5LsMWhAoRoM1z0vaEUk3m3u6wJiJR4rRNmOdMX4b1QqHUhw0MwlErKq/I0HNi+K2XQ0ddOZ2/5rczrIb8erxhDKLPz9ErQDxycxMzhf2GAC6d8wbLH2oA403skoG1YIg/KnyF6EKBznEFI7qPkRLhZ+SHSzNGx0RvG6qcz5WqxucLyvSfF5rxXVE5VKrzKDwGISBPQfYfhEPMwgdXDT3EzEzq70oa2l8WiZ45uvnSo9+SBYJbwAPsW8XopCvpFjRS+yflnpbHkMOhkk1t+9Sw+pp9w7NHnxqnZT5KD3BU1SpIUPGJ2xm4NdTv2yDxuuRhPY1jKaGL4VzGMRTy8GBi/ebZyUgySmwZQ+P2gTbBvo+cCukeAgbpu+fS7Q62FDT96mlPF3t8nrDBmdo1CFz3CNbRpcHuSZ1ukMmTiwlJ2ZBYUL9rAa9QrVDK/NoK31OpQfGo5nqBCqqnm78PvLBMUqoMEBq6777A4R3nxnRF22707oNeH+B2Qb/8mkG1Q1Bj59BJL2X9sD6zOd6Bh+OB0p2qYNM=
    AUTHENTIK_SECRET_KEY: AgCjd87A5XtJVDyVCfySYE1mpwNtlB9nbgIqc26bVodV70VrWUr4ZQPxa1DfLaPBMComvtoAXh8P0AcgFkRBiBT2+PlFG/xO9sxZht8t4WBx117/cyECtd8JKl0xnfc693GPxOkCc3gq0j6r866XL5QACW3h0gDhC2if4em5k3eXYWe2ITocOmYN5dzABOhYgU0x1kqk5rj22tCu70KB8kMdZzMG3z8y7RwVZdjLuWk/0e1JERCLfanQeYJxlaH6+fI1iGBqV0MZbHjnQJ8xUqyEt8qEhEeb1f0/w4J6xAgfJYVPaK6Z/Gj+Na7VFChQvs8TuQE1uABz1loVHuwpvXrIKXVO//4BNqPy6vF/uWlJW1/Q/f5N1imMQDhO7AcU5VHAA0WqHHaLBEyMGe2JBhY39TaB3RZqetrzIFUOrGpk8YW51zPsTFoOHTdOhi0Hzuo/mGBesnaVgYFwxm9mJJDuf1Se6b/MqGvCgzGcH1kQcxFB4DFvl86vAFTDa4Mepplv3bHN/9+3z1oV0biOzbNilQ61/5Fd5FV/YsN7IQca7GYuDGnD15rl+g4M544jy9QXaUbL422BzT8J33abRQlzX4i2oFdiMR9XesqbID1+CKsEJPmVMN5Bc/RpDG/m/a7DQGAOZwtwY6Vo11CsvVAY6LH14uBCTXaUZxQWlUiC/6zNlt9Fw153ydX6hoHpnOzz8Uk7RMFOfOymKWtTopCPK+wrbUSuv46CnS9zhOSy3VjDuwmGPl+drW3APg==
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
