apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nginx-external
  namespace: ingress
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress
  version: 4.12.3
  valuesContent: |-
    controller:
      ingressClassResource:
        name: nginx-external
        default: false
      ingressClass: nginx-external
      config:
        # Trust forwarded headers
        use-forwarded-headers: "true"
        
        # Map Cloudflare scheme to a real scheme
        map-hash-bucket-size: "128"
        http-snippet: |
          map $http_cf_visitor $real_scheme {
            default $scheme;
            ~*"https" https;
          }
        
        # Override headers sent to backends
        proxySetHeaders:
          X-Forwarded-Proto: "$real_scheme"
      service:
        annotations:
          nginx.ingress.kubernetes.io/auth-url: |
            https://auth.glazrtom.fun/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |
            https://auth.glazrtom.fun/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid