apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.class.bulk.name }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: {{ .Values.class.bulk.replicaCount | quote }}
  staleReplicaTimeout: "30"
  fsType: ext4
