apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      initContainers:
        - name: init-perms
          image: busybox:1.38
          command:
            - sh
            - -c
            - >-
              mkdir -p {{ range .Values.global.sharedMedia.dirs }}{{ $.Values.global.sharedMedia.mountPath }}/{{ . }} {{ end }}&&
              chown -R {{ .Values.global.user.uid }}:{{ .Values.global.user.gid }} {{ .Values.global.sharedMedia.mountPath }}
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: media
              mountPath: {{ .Values.global.sharedMedia.mountPath }}
      containers:
        - name: transmission
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: PUID
              value: "{{ .Values.global.user.uid }}"
            - name: PGID
              value: "{{ .Values.global.user.gid }}"
            - name: OPENVPN_PROVIDER
              value: "{{ .Values.env.openvpnProvider }}"
            - name: OPENVPN_CONFIG
              value: "{{ .Values.env.openvpnConfig }}"
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.usernameKey }}
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: {{ .Values.secrets.passwordKey }}
            - name: TRANSMISSION_WEB_UI
              value: "{{ .Values.env.webUI }}"
            - name: TRANSMISSION_DOWNLOAD_DIR
              value: "{{ .Values.global.sharedMedia.mountPath }}/downloads/complete"
            - name: TRANSMISSION_INCOMPLETE_DIR
              value: "{{ .Values.global.sharedMedia.mountPath }}/downloads/incomplete"
            - name: LOCAL_NETWORK
              value: "{{ .Values.env.localNetwork }}"
            - name: TZ
              value: "{{ .Values.global.timezone }}"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: {{ .Values.global.sharedMedia.mountPath }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: transmission-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: transmission-media-pvc
