apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-media-transmission-pv
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  capacity:
    storage: {{ .Values.global.sharedMedia.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-bulk
  volumeMode: Filesystem
  claimRef:
    namespace: {{ .Values.namespace }}
    name: transmission-media-pvc
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: {{ .Values.global.sharedMedia.name }}
    volumeAttributes:
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
      share: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-media-pvc
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.sharedMedia.size }}
  volumeName: shared-media-transmission-pv
  storageClassName: longhorn-bulk
