---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCH8UB62mU4d4xYEELzCrVK/puLN4QWDPuQANpD+nZnAK/r4yUh4BhBgSLMM3gEw/72WKMGW/+EjpYylDPE3PzsSc+DU/3WKT9v/IMRMRNRNl8wVvcxyOn3382rMDJlk4La9MGjkRfLTd9OjsTaGTnDVbYBlE3s93hrgMVnhRacgn8+9d8McMPOPAPvE37ae3jkNIAW5n6HKL/icT0jUVncHo+Q0VjLzDP08bdv+TvEqUmnBMngWLbwmRYiyyPtOe/rzyyqE7ViOZQtJrsvD0wN4vmiWr9TxtLGoa0hXn7sUqRL/JrKGZcQcwPhLvjGJvecIojlf0iokXoFU+TdxvoYD9QpV6nZO+pOic91WNsgpVU1Q0wJ75giO2cdcM4pC4hZyykieRq+jn+8MhCydnLiXgdj1yKH6Cyxi/FKKdpsO1XW5x75FTsVE1t2pu6ZN81Aj2ZFTNareux6vMkBEUw44CEtzm+DYpFgm9LGOyHpBmZCnw86b0967gBtF8bu/TYxu2Eou9TaejUDWTMXQ+ygagCH25tU2dfyJLIHpIwe3Y+/5aMhYOUkKAjUYH67Q9KdMxnHPdKfOEM9Dkoxlji44Y/RfqRzXhtH+hh68NVuvupHK/fMC7aw5CSx0KaPFcmxtC4PijV2twTbeWzEMJ+FH6N3CUpfAgf6jTOsnh9ijYA9Rq8gXVYIDdkF/73yr4pb0yhmtTczjbmVKtbE8aq553Tt7AzGIBVGdh8pWPRwl0rvETmRJcziwpSQk+eMQ98CGhbL+jJSopbBh2TkyTREOFNAsIERdN0vLcF+kSK4uZRVYTC6Ib6rKMe/nHMly4s+T495/f0qRhYc/mh78jq5x/ROnE/yvMoVOxqjfE2UQLWnC7RCVE7bRF/x9c83SCnP8tLw2MhGsrC/HEDsItodGZJ9jzsjXz06zgb7+OgzUwL6ZWScg5JYAYwwYDsp8D1G5A7697lZp8k2jVR+h90=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      name: ghcr-credentials
      namespace: default
    type: kubernetes.io/dockerconfigjson
