---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCTkpyfmvgzi4+TyBzKFUjakfS7CvPItpfpHGE7XK6aGiG5Muo+9M20itOCZolSp1K+re2TWXBMwC66LgrjsRLQqu87pA6XTYHVUdrNM7VyDuX6YCNkUAOH1wQB00fH7jB6Gk3s6sXr+HXQ07HlsPxIYH7qobCmjS+gi5xHkaTi6lHNbNGO9U6xJje2TPwD6rx/bcLg+52JrSVNIkRmhpNI5sqvE3MWhz9Y1BCBinEUvKiATYHrslnIrPYhFgoL4hLafRkV6oB5umJlyllj4vHf0BSCe0XR51grBXN8fV+8FzWS12QWYbuzNoq02leEbLEjBJN10Q5xwS8BiGPZTPylIqv1nbWJcIc8PlmND9LsBA9DE3oRRdmE4y3WKBzwAvxLi2w801aLaaivUGSW3gArFtyNU84DZH7/9UjZUpXPfapI/DpBOc63zjOzNWe0Y20t2FwfbH9/Fo7aEycFkalekLNp6PsWyIFO1fPVJidPb82tWiWZ5Hp+3MwgvVfLDMpuemKb3mKHQoluBsJ1Mskyy8WOOapeoIMPUtiG/fNFP8zzBNFKzC/aC/DNxFs6Puj/ladp30QOBpiKfIGQpiZzJ4h6zOf6cUm155hzbNzrZLj8CwPDVYep9LBOTfas3lzFLs03HResRJ2l6pTKnbIjfhdzqbPoRpw1earo51mrMf5bD5ceKihI4P4tVKTHKj8RYcEYJop5uJoxulRFLrC6ZkB1yvRM6rU232mulw3WFShdY+zyN0RI1yKWzsV3TbdmWLjYAhDn6qRKALNEjnuggeES0UXsr3eViQ9JV9Gxumk9eUPIeJI3QptnkkW5DjybM/RA8dX05i2BTW4PUlc327QhHmqdbXL0THtvMpgorx6Hiv472jC7hTHZVTzwqOTKsTMyEMAlqZxwxYrUrWreyIV9nbJK1cnmaV/ZNM87kkMbcfaUKXqLKoM4ass6qDCq2P2L/YXR9ULZLzlyW40=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      name: ghcr-credentials
      namespace: default
    type: kubernetes.io/dockerconfigjson
