---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCA9nz15NSMaIvFPB8DwpGMIyXPmNe7p+42mHTakwfJlo5Z9rbpNBedOLpY7n+nWn7jOrdffLIG1NJk4tSxYEu+gthXD/IR2Gm5xllWKu1mD93lpvCT/+d5jedqOIt/ycRC94mvh5b/8USclWuHQgF0nNPDxj32SnMywdu8JWaHxqp/qZAXJvyYguO0eu5mtFOxW1FGytSSTbazi7zBouuM3iUjrbGBax0n7Z9nBv0XlauG25uNliBeGDx47Nh4jtvFuraG2CryoCVQbcUngwYCUKeRb/Rhc/dXzhsqMqSj/+NA5fZdMEjr75nJU+blat2nwuGj72pEwaTHFRapsvuR3Kt/7Skkd7F7SmkSb13N5oVy3ILI2wjwD+KN31eRresrdXwYncODBZ16rlBCVXtgPByqMiGOcTI7y6PpKDxMdMA1aZhX1XhsoLRZivukU03WVPtMgOW4BdPh4i/w9oSVV/gWqdpNScYsPgmP76A9kncE0stnEbTADgPI3yjQyIvNcF3bfxTtwOzxgMc5k6MFfAi4JqScRXQY9D+l6WXO2AI1sx49yShlHbZPdDrEVLriZgDGvSY+luAvmZyzO88IkVsJH00TRDHy4OcwBNOU0bglLgi3ojil6WX5rA6BbUj1ak5ju0lbzmOJSThsE2tf+mGLgh6Xka3bWgylK4V3mu/eGZBNNP9K+hRAg/K5Y1qEmDKoHHZMv5FnKsKl47XsJAeXVTAdwVUEvdauSPB4kYb5zMlZtp26cy3HTkQtkNRvz89tGe2vomvqTypqxTWgiDbYo8VTqxq6w72mMXaTd1/pVEvTsklXGoGJdpSHPMDTI9CN8M4vuNnFss6iQ5fh94cOSQSHOcKiL61oVNVlLVVCJ8ohP3Pt5S/3PaPgYcvavov8Ecy9vULlicEKjfQl1iKUoxdrqsH2qHgmWLl/kHkivOzWUBPSAgAKrmrT8SkoKboXXcN5acao1pLvMV8=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      name: ghcr-credentials
      namespace: default
    type: kubernetes.io/dockerconfigjson
