---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCAIUQACcxWIbF8POGDH0IdI9GYrW/ZJxrYRSmkcSiGg8tY1CKNJigNrCVtMB+Jz57WoTorh3cU3uVPi7SKtEKmZYIOApyS+eBXMqYiTJj0umMJBwaufwDYGLltbIoJphAo7U1Y5butrOvurvMEFk21dbGKMMrK7FvKtbJt66BO6grOIV/F5kUTrE4DP/ZzdYYgXi5rGV7riJeWBcIZ4Z+K4ncMxkdMgcGvhBOR/lskfhHGd0OAMgx5Ge3c+8+f8pSAbVH8FIpdCpf0jhuINLdMd4DlqTL8LTTUWucKYjoDccPe5UguiSMJndDjcLB7BK/wiHVY7GIJYa+JpniSw719DGetLOfHYIcZ0JBMF2dCm++JuJVwpd0PH3Karlk4/ojpytFi9Is472e3YlUQ/fIBFKujcqoJjsXKlAEUbOIoYx3STgLpOjwVRMEu4ZFcnHGutPaIjpfNorcV6y9PfQW0QF+Ba/HSGATrrIvFjg969RpOYQzHsjDFVxs4+2L9DuEVDkqL2/a0g5beWE2FvuBXUeV98U0m9DTuLAvIZUt7MYvtsnrLMNOQjTTIq7i+Iw5F2+EsGIBwjum9rrc97EtM4mfl8ZEqUySlCSAcZ+gfVB2+3bZkDyml1lB2flC7nGC4GYIfUkopHWhmwruCzm8BckVaQwITDGA855lBe9DZdmbELm4lX4vHVOJ+y1W6IhJjk6r51Apw1Es7bhu2Vx1Totcg+sWkRi8FvUT9OGrgHjqfVZneTQ/9n8FyexqU+x480kXQYeNn1npHCoKs+Qs5MCK6e5kzswW1HA23ADU+Gns4Gkuaj7KEFVIX3+76ZfvcXa+Jp2xwZ2+iYL3N59oCoy0m45TL3BWYgvb5HiDeK3A8N8AUwsR44VLwE0M61yQa8C8nm/Wy4TnTKDG/zMy5vnXdqss0o5p/AWRfWkyLAsPBMCG2ToNs1jbx5ev+19iPO3r6XyLMgf7DnFYwkRA=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      name: ghcr-credentials
      namespace: default
    type: kubernetes.io/dockerconfigjson
