---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCBTN8R9PFxPa/3k+bx0C0ww2DK8FjD5007Qr6yKs0EDLVtPYxJe6OyESBvYTsTsC/7M34C6oQaUMOslodJgbPhQiz8p0IpRM41DYjkX9zP1MCkz+dzVhskMOSrNfPR8Z9gPfNB2orgygNOkhkSq6f+KEyFG2oyUyf2WR1+sMsXEU+x7xNZMckl6E3UvZVfgeNNGc/tEXi8RkBzvw088ZyA3bAsrTLsWrwaysY7Whpc9tABTz+6ur3RyLCd08qPgEj3Cj/2VdeL0mbvRYKlsVFnlyFWBuf1sLJlIp8Vd2EFDVuMBl3uUKJF1MaQK2Clng5wY9wKW0UN3x+5ETDGzocVAIldDmwjbi3J1y8IE3ckOHfZBtLtDN2xFZ2EWrWIdSYKAtNjf691RbG4+V1BBCPsYgLNpOULsVWYQrid6TXnw+CH7OTikexXLvmbmpxMTni/gF1Y1OV/Tnr8D27z5fPnykpbBUJ/WNgP5LLdl6GF8SPDT2aIXMrIZLrDVI/ed+D4u5SuYzn8zdDXyT+hhneCBUYoXfDK96t6dTEb2YIIINTznGhUQ3zYlGeXVNrj1ZKgl75rxYWy8H4a9QSfrcvHH3hgd/2PMzwqlwHS/7/yDVWSm2TFVf7mlzTSKI2Cjjb6KXT7zvBXhjaOlOE60XjWSESlGwJ4r8dPjScfc7vkoxRXLgjvm2Efm6BEkCLu3Cw5lAJFb3mxS/8wVc0kF24KVUxAFw6ysmdlLvZPOvRvmwHiGFCEcM5+XCVg1nDCsAJUKDVzbazBBtx/E4hy1ckUitwjrRPx4+mL578MQVnCWV3L+xG57IvNCAXgkGJGzQVk1nTbHLqZIuhUQ/kfysJZqzOhfQVrSRMmv766T+tLtJbabKVPDqk530YmZDBbGs2wWGtSf264eQJBMIDShd7/0epf4Cn1X8TNC5Q8s3mhNu58t4XRxWL5G0PvwAU8jrrHlcu52qmvcABvNb5l4vg=
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      name: ghcr-credentials
      namespace: default
    type: kubernetes.io/dockerconfigjson
