---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: windscribe-auth
  namespace: default
spec:
  encryptedData:
    password: AgAM20wvi8LcWEm8T0zkiZNj9AXy7BdFGaRirPQrBRfuePyQiZpVPit8AyrDpFu8qqXsQogpteAJ9ikH1g9IsLepjH6SMmZuZzZW02EapyJJ4ndgDW8E71k1Yw6GMgFJ7sfeTNDhtQEtzpm0f7wv1XpqMF5Avmll8MFRQ+vzB3eAt248LIEUrtzRXelMg/8KAA9xqPtEoR7M3IwRCP39q3QrEcc+20P8lKZy0uYmGZMyPNjz9TumE17rDHK93P1Pkzvz91YU9a394uoH3oCHbI28pm5oMh4yLiIX/Hxy7139c+5zY4bChgaPeiHqexEAyzhvZhj8k6ZawDOwd7tEGxpuzBgUVBWJLq9sI9oiRKmdpHhxeU1aXyaEATmFH7esS9DajOAnt65NA9Qijkqqgl2kHyhf3x185yz0zbUiZY0Y87BxZC/YSu6Qke8m/EFOCWhJqInRNufcjx+OurjToVg8QOOH+i3nmwlKO7kvIrXmhmTQEmcx2MCxjKiP+8JydHCbpCSq1sXQlX+G9grIqF4q9ZqxFRi3tZuiAVfGlNz53mMw1irH7GiylRIfovkYrPs7OFtumjTJe6yrR+e5N2QlGpE4YVdNBrSQ95Z1rWgwVwS+q712qJod/wSea5TRW8kBlkjn5uBN+UoFhtIHRcbK3xTqyIQKDI4tycYsrtMls9+2saEF2VQUzk8I5OhDvVYWWTAZZj4KLo7u
    username: AgC1XfqDcclUB54yaYbgpShD7AvhEYsdGGfXT2pjmaZnERDHnGw2CBtZYCIJ74XhakmpOxv5Zz0ZA4pUT6OaORrqg9DS7eWP5ji8gDWXzgxSBBRQbRQW1C9/bCFjks3x1CRmfiv6DZeynx2p8rNi6jjHV5rsH90d9HrsOtYGXqcl7iQYJaeHEyE2xLC0O/DiSvj4MlVCYw1Ij9f8Ea8GbIVUq05AkYd4fk3ALDejJiQusIu19aPh4I76U9AI6oYNG3T2bOXC5mtGg83/q0YiBzJ7ZIPR5uyVE6QTPyrUQyB2KqHRpnSfkfqXYmDlzkPETKjPhnSeVZ7PNsUVUoq9VGyxCMP/+WwZ0EQ47p+j6QW8GV/vJ/a5tNRwGqHesbn47gqjDUHGm1H/PPrZeVEfWOawpwkbPknzT+DIOX8iIlu9BR3qoQJMiXhh1nct23wMX2Sw6etMDUGyZQ8yJneRUE4yv6BRmtlUTYQmc1m7Xpv39KkKj/ZpQxYY929hv2zwZaGzEZJ0TPnjr70UaA+kOX7MD2G1oB1/j9GFLl80uPUwx549Xn3Acx2kU7LEs/S52oeqhEy+IzFxl3Q25uiXc/JL7MZXAFdG+wdca+gdwqb2I637BmTw4UpwYYF559jg9d527iQYGzvBaMg//RtVDBj0lPa/mgmwicoA+YtRu1+OpTsLzgHFIMR1a9VWS8MesCe4As8BDm3uLwn51PkgY7Xn
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: media,transmission
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: media,transmission
      name: windscribe-auth
      namespace: default
