replicaCount: 1
namespace: transmission

image:
  repository: haugene/transmission-openvpn
  pullPolicy: IfNotPresent
  tag: "5.4.1"

env:
  openvpnProvider: "WINDSCRIBE"
  openvpnConfig: "Prague-Vltava-udp"
  webUI: "flood-for-transmission"
  localNetwork: "10.42.0.0/15"

domainPrefix: transmission

volumes:
  config:
    size: 1Gi
    storageClassName: longhorn

secrets:
  name: windscribe-auth
  usernameKey: username
  passwordKey: password
