apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media
  namespace: argocd
  labels:
    homelab/tier: apps
spec:
  generators:
    - list:
        elements:
          - name: media-global
            valuesFile: values-global.yaml
          - name: media-personal
            valuesFile: values-main.yaml
  template:
    metadata:
      name: '{{name}}'
      labels:
        homelab/tier: apps
    spec:
      project: default
      source:
        repoURL: https://github.com/glazrtom/homelab.git
        targetRevision: HEAD
        path: media
        helm:
          valueFiles:
            - ../global/values.yaml
            - values.yaml
            - '{{valuesFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: media
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
